version: "3.8"
name: Techno_Deploy
services:
  db:
    container_name: Techno_DeployDB
    build: ./DockerFileSql/.
    env_file:
      - ./.env      
    
    restart: always 
    volumes:
      - /D/source/TechnDeploy/Datas/data:/var/opt/mssql/Data
      - /D/source/TechnDeploy/Datas/logs:/var/opt/mssql/log 
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
  webserver:
    container_name: Techno_DeployWS
    build: ./Back/.
    env_file:
      - ./.env
    environment:
    #$DB_HOST contiendra l'adresse ip + le port (cfr .env)
      - DB_HOST:$DB_HOST
    depends_on: 
      - db
    ports: 
      - 3000:3000
    restart: always 
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
  frontend:
    container_name: Techno_DeployFront
    build: ./Front/.
    env_file:
      - ./.env
    environment:
      - apiUrl=$webserver
    ports: 
      - 4200:4200
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

  
  #pour voir les logs ==< docker-compose logs -f SERVICE
