name: "The Best App 4 Ever"
services:
  db:
     container_name: BestAppDb
     build: ./DockerFileSql/.
     env_file:
      - ./.env
     volumes:
       - /D/source/TechnDeploy/Datas/data:/var/opt/mssql/data
       - /D/source/TechnDeploy/Datas/logs:/var/opt/mssql/log
  back:   
    container_name: BestAppBack
    build: ./Back/.
    env_file:
      - ./.env
    environment:
      - DB_HOST:$DB_HOST
    depends_on:
      - db
    ports:
      - 3000:3000
    restart: always
    
  front: 
    container_name: BestAppFront
    build: ./Front/.
    env_file:
      - ./.env
    ports:
      - 4200:4200